language: node_js

node_js:
  # https://github.com/nodejs/LTS
  - "6"  # ends April 2019
  - "8"  # ends December 2019
  - "10" # endsApril 2021

sudo: false

env:
  - SINON_VERSION=^5.0.0
  - SINON_VERSION=^6.0.0

cache:
  directories:
  - node_modules

after_success:
  - npm run coverage-travis
  - npm run coveralls
